# Change prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Options
set -g renumber-windows on  # keep numbering sequential
set -g mouse on

# True colors support
set -g default-terminal "tmux-256color"
set -a terminal-features "tmux-256color:RGB"

# Theme: status
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""

# Theme: borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# Keybindings: split
bind | split-window -h
bind - split-window -v

# Keybindings: windows
bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind r source-file "~/.config/tmux/tmux.conf"
